let a = document.getElementsByClassName("top_img")[0];
a.style.width = "100%";
a.style.position = "relative";
a.firstElementChild.src = "./bg-pattern-1.svg";
a.firstElementChild.style.height = "330px";
a.firstElementChild.style.position = "absolute";
a.firstElementChild.style.right ="-157px"
let logo = document.getElementsByTagName("header")[0].firstChild;
logo.src = "./ineuron-logo.png";
let appimg = document.body.querySelector(".app_img");
appimg.firstElementChild.src = "./illustration-app.png";
appimg.style.width = "100%"
let bubimg = document.createElement("img");
bubimg.src = "./bg-pattern-2.svg";
bubimg.alt = "bubleimg";
bubimg.style.marginLeft = "-390px";
bubimg.style.marginTop = "100px";
bubimg.style.height = "400px"
appimg.append(bubimg)
let bgimg = document.createElement("img");
bgimg.src = "./bg-main-desktop.png";
bgimg.alt = "mainbg";
let mainbg = document.querySelector(".mainbg");
mainbg.height = "1400px";
mainbg.style.position = "relative";
mainbg.style.backgroundImage = "url('./bg-main-desktop.png')";
mainbg.style.backgroundSize = "1300px";
mainbg.style.backgroundRepeat = "no-repeat";
let mainmobi = document.createElement("img");
mainmobi.src = "./bg-main-mobile.png";
mainmobi.style.position = "absolute";
mainbg.append(mainmobi);
let ios = document.querySelector(".iosDownload");
ios.firstElementChild.src = "./icon-apple.svg";
let andriod = document.querySelector(".androidDownload");
andriod.firstElementChild.src = "./icon-android.svg";
let foo = document.querySelector(".footer_logo");
foo.firstElementChild.src = "./logo (3).svg";